import sys

with open('core/src/engine.cpp', 'r') as f:
    content = f.read()

first_ns_end = content.find('}  // namespace prizma')
if first_ns_end == -1:
    print('Could not find namespace end')
    sys.exit(1)

first_part = content[:first_ns_end + len('}  // namespace prizma')]

heuristic_impl = ''

heuristic_impl += '\n\n// \u2500\u2500\u2500 Heuristik / Dinamik Kural Motoru Implementasyonu (v1.3.0) \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n\n'

heuristic_impl += 'int Engine::calculate_heuristic_score(const DomainHeuristics& h) const {\n'
heuristic_impl += '  if (h.total_requests < heuristic_config_.min_requests_for_scoring) return 0;\n'
heuristic_impl += '  \n'
heuristic_impl += '  int score = 0;\n'
heuristic_impl += '  \n'
heuristic_impl += '  if (h.total_requests > 0) {\n'
heuristic_impl += '    double tp_ratio = static_cast<double>(h.third_party_requests) / h.total_requests;\n'
heuristic_impl += '    score += static_cast<int>(tp_ratio * 30);\n'
heuristic_impl += '  }\n'
heuristic_impl += '  \n'
heuristic_impl += '  if (h.total_requests > 0) {\n'
heuristic_impl += '    double active_ratio = static_cast<double>(h.script_requests + h.xhr_requests + h.fetch_requests) / h.total_requests;\n'
heuristic_impl += '    score += static_cast<int>(active_ratio * 25);\n'
heuristic_impl += '  }\n'
heuristic_impl += '  \n'
heuristic_impl += '  if (h.suspicious_params > 0) {\n'
heuristic_impl += '    score += std::min(h.suspicious_params * 5, 20);\n'
heuristic_impl += '  }\n'
heuristic_impl += '  \n'
heuristic_impl += '  if (h.unique_paths > 10) {\n'
heuristic_impl += '    score += std::min((h.unique_paths - 10) / 2, 15);\n'
heuristic_impl += '  }\n'
heuristic_impl += '  \n'
heuristic_impl += '  if (h.total_requests > 0) {\n'
heuristic_impl += '    double block_ratio = static_cast<double>(h.blocked_requests) / h.total_requests;\n'
heuristic_impl += '    if (block_ratio > 0.5) score += 10;\n'
heuristic_impl += '  }\n'
heuristic_impl += '  \n'
heuristic_impl += '  return std::min(score, 100);\n'
heuristic_impl += '}\n\n'

heuristic_impl += 'void Engine::update_domain_heuristics(const std::string& url, uint32_t type_bit,\n'
heuristic_impl += '                                      const std::string& hostname,\n'
heuristic_impl += '                                      const std::string& doc_hostname,\n'
heuristic_impl += '                                      bool third_party) const {\n'
heuristic_impl += '  if (hostname.empty()) return;\n'
heuristic_impl += '  \n'
heuristic_impl += '  auto& h = domain_heuristics_[hostname];\n'
heuristic_impl += '  h.domain = hostname;\n'
heuristic_impl += '  h.total_requests++;\n'
heuristic_impl += '  h.last_seen = static_cast<int>(time(nullptr));\n'
heuristic_impl += '  \n'
heuristic_impl += '  switch (type_bit) {\n'
heuristic_impl += '    case T_SCRIPT:   h.script_requests++; break;\n'
heuristic_impl += '    case T_XHR:      h.xhr_requests++; break;\n'
heuristic_impl += '    case T_FETCH:    h.fetch_requests++; break;\n'
heuristic_impl += '    default: break;\n'
heuristic_impl += '  }\n'
heuristic_impl += '  \n'
heuristic_impl += '  if (third_party) h.third_party_requests++;\n'
heuristic_impl += '  \n'
heuristic_impl += '  size_t path_start = url.find("/", url.find("//") + 3);\n'
heuristic_impl += '  if (path_start != std::string::npos) {\n'
heuristic_impl += '    std::string path = url.substr(path_start);\n'
heuristic_impl += '    h.path_counts[path]++;\n'
heuristic_impl += '    h.unique_paths = static_cast<int>(h.path_counts.size());\n'
heuristic_impl += '  }\n'
heuristic_impl += '  \n'
heuristic_impl += '  static const std::vector<std::string> suspicious_params = {\n'
heuristic_impl += '    "utm_", "fbclid", "gclid", "_ga", "_gid", "mc_", "_ym_", "_ga_",\n'
heuristic_impl += '    "ref=", "source=", "medium=", "campaign=", "content=", "term=",\n'
heuristic_impl += '    "click_id", "affiliate", "aff_id", "subid", "sub_id", "cid"\n'
heuristic_impl += '  };\n'
heuristic_impl += '  \n'
heuristic_impl += '  size_t query_pos = url.find("?");\n'
heuristic_impl += '  if (query_pos != std::string::npos) {\n'
heuristic_impl += '    std::string query = url.substr(query_pos + 1);\n'
heuristic_impl += '    for (const auto& param : suspicious_params) {\n'
heuristic_impl += '      if (query.find(param) != std::string::npos) {\n'
heuristic_impl += '        h.suspicious_params++;\n'
heuristic_impl += '        break;\n'
heuristic_impl += '      }\n'
heuristic_impl += '    }\n'
heuristic_impl += '  }\n'
heuristic_impl += '  \n'
heuristic_impl += '  h.heuristic_score = calculate_heuristic_score(h);\n'
heuristic_impl += '  \n'
heuristic_impl += '  if (heuristic_config_.auto_generate_rules && h.heuristic_score >= heuristic_config_.min_score_threshold) {\n'
heuristic_impl += '    maybe_generate_dynamic_rule(hostname);\n'
heuristic_impl += '  }\n'
heuristic_impl += '  \n'
heuristic_impl += '  int now = static_cast<int>(time(nullptr));\n'
heuristic_impl += '  if (now - last_cleanup_time_ > 3600) {\n'
heuristic_impl += '    cleanup_old_heuristics();\n'
heuristic_impl += '    last_cleanup_time_ = now;\n'
heuristic_impl += '  }\n'
heuristic_impl += '}\n\n'

heuristic_impl += 'void Engine::maybe_generate_dynamic_rule(const std::string& domain) const {\n'
heuristic_impl += '  auto it = domain_heuristics_.find(domain);\n'
heuristic_impl += '  if (it == domain_heuristics_.end()) return;\n'
heuristic_impl += '  \n'
heuristic_impl += '  const auto& h = it->second;\n'
heuristic_impl += '  if (h.heuristic_score < heuristic_config_.min_score_threshold) return;\n'
heuristic_impl += '  \n'
heuristic_impl += '  if (dynamic_rules_.find(domain) != dynamic_rules_.end()) return;\n'
heuristic_impl += '  \n'
heuristic_impl += '  if (static_cast<int>(dynamic_rules_.size()) >= heuristic_config_.max_tracked_domains) return;\n'
heuristic_impl += '  \n'
heuristic_impl += '  std::string rule = "||" + domain + "^$third-party,script,xmlhttprequest,fetch,important";\n'
heuristic_impl += '  dynamic_rules_[domain] = rule;\n'
heuristic_impl += '  \n'
heuristic_impl += '  if (debug_enabled_) {\n'
heuristic_impl += '    std::fprintf(stderr, "[PRIZMA HEURISTIC] Dynamic rule generated for %s (score: %d): %s\\n",\n'
heuristic_impl += '                 domain.c_str(), h.heuristic_score, rule.c_str());\n'
heuristic_impl += '  }\n'
heuristic_impl += '}\n\n'

heuristic_impl += 'void Engine::cleanup_old_heuristics() const {\n'
heuristic_impl += '  int now = static_cast<int>(time(nullptr));\n'
heuristic_impl += '  int window = heuristic_config_.request_window_sec;\n'
heuristic_impl += '  \n'
heuristic_impl += '  std::vector<std::string> to_remove;\n'
heuristic_impl += '  for (const auto& [domain, h] : domain_heuristics_) {\n'
heuristic_impl += '    if (now - h.last_seen > window * 24) {\n'
heuristic_impl += '      to_remove.push_back(domain);\n'
heuristic_impl += '    }\n'
heuristic_impl += '  }\n'
heuristic_impl += '  \n'
heuristic_impl += '  for (const auto& domain : to_remove) {\n'
heuristic_impl += '    domain_heuristics_.erase(domain);\n'
heuristic_impl += '  }\n'
heuristic_impl += '  \n'
heuristic_impl += '  if (debug_enabled_ && !to_remove.empty()) {\n'
heuristic_impl += '    std::fprintf(stderr, "[PRIZMA HEURISTIC] Cleaned up %zu old domain entries\\n", to_remove.size());\n'
heuristic_impl += '  }\n'
heuristic_impl += '}\n\n'

heuristic_impl += 'void Engine::set_heuristic_config(const HeuristicConfig& config) {\n'
heuristic_impl += '  heuristic_config_ = config;\n'
heuristic_impl += '}\n\n'

heuristic_impl += 'std::string Engine::get_dynamic_rule_for_domain(const std::string& domain) const {\n'
heuristic_impl += '  auto it = dynamic_rules_.find(domain);\n'
heuristic_impl += '  if (it != dynamic_rules_.end()) return it->second;\n'
heuristic_impl += '  return "";\n'
heuristic_impl += '}\n\n'

heuristic_impl += 'std::string Engine::dynamic_rules_json() const {\n'
heuristic_impl += '  std::string out;\n'
heuristic_impl += '  out += "[";\n'
heuristic_impl += '  bool first = true;\n'
heuristic_impl += '  for (const auto& [domain, rule] : dynamic_rules_) {\n'
heuristic_impl += '    if (!first) out += ",";\n'
heuristic_impl += '    first = false;\n'
heuristic_impl += '    out += "{\\\"domain\\\":\\\"\";\n'
heuristic_impl += '    append_json_escape(out, domain);\n'
heuristic_impl += '    out += "\\\",\\\"rule\\\":\\\"\";\n'
heuristic_impl += '    append_json_escape(out, dynamic_rules_.at(domain));\n'
heuristic_impl += '    out += "\\\"}";\n'
heuristic_impl += '  }\n'
heuristic_impl += '  out += "]";\n'
heuristic_impl += '  return out;\n'
heuristic_impl += '}\n\n'

heuristic_impl += 'std::string Engine::heuristic_stats_json() const {\n'
heuristic_impl += '  std::string out;\n'
heuristic_impl += '  out += "{\\\"tracked_domains\\\\:";\n'
heuristic_impl += '  out += std::to_string(domain_heuristics_.size());\n'
heuristic_impl += '  out += ",\\\"dynamic_rules\\\":";\n'
heuristic_impl += '  out += std::to_string(dynamic_rules_.size());\n'
heuristic_impl += '  out += "\\\"config\\\":{";\n'
heuristic_impl += '  out += "\\\"min_score_threshold\\\\:";\n'
heuristic_impl += '  out += std::to_string(heuristic_config_.min_score_threshold);\n'
heuristic_impl += '  out += "\\\"max_tracked_domains\\\\:";\n'
heuristic_impl += '  std::to_string(heuristic_config_.max_tracked_domains);\n'
heuristic_impl += '  out += "\\\"request_window_sec\\\\:";\n'
heuristic_impl += '  std::to_string(heuristic_config_.request_window_sec);\n'
heuristic_impl += '  out += "\\\"min_requests_for_scoring\\\\:";\n'
heuristic_impl += '  std::to_string(heuristic_config_.min_requests_for_scoring);\n'
heuristic_impl += '  out += "\\\"enable_ml_scoring\\\\:";\n'
heuristic_impl += '  heuristic_config_.enable_ml_scoring ? "true" : "false";\n'
heuristic_impl += '  out += "\\\"auto_generate_rules\\\\:";\n'
heuristic_impl += '  heuristic_config_.auto_generate_rules ? "true" : "false";\n'
heuristic_impl += '  out += "}}";\n'
heuristic_impl += '  return out;\n'
heuristic_impl += '}\n\n'

heuristic_impl += '}  // namespace prizma\n'

with open('core/src/engine.cpp', 'r') as f:
    content = f.read()

first_ns_end = content.find('}  // namespace prizma')
if first_ns_end == -1:
    print('Could not find namespace end')
    exit(1)

first_part = content[:first_ns_end + len('}  // namespace prizma')]

ns_end = content.find('}  // namespace prizma')
if ns_end == -1:
    print('Could not find namespace end')
    exit(1)

with open('core/src/engine.cpp', 'w') as f:
    f.write(content[:ns_end] + '\n' + heuristic_impl + '\n}  // namespace prizma\n')

print('Fixed engine.cpp')
